### ISSUE TITLE
no man page

### ISSUE THREAD

**Issue by ggl** [httpie/httpie#477] opened 2016-06-08 07:30 UTC
Lacks documentation other than a basic usage message when run w/o arguments. A man file would be nice.

**Comment by stefan2904** [comment] 2016-06-13 21:05
One could add the manpage from the Debian project: https://sources.debian.net/src/httpie/0.9.2-1/debian/http.1/

It's rather short, but at least there is one. :-)

**Comment by csurmont** [comment] 2017-04-11 10:40
It seems like the http(1) manpage has been added, but there is issues with it. the headers only option is --headers or -t, but it is --headers or -h for httpie instead.

**Comment by merwok** [comment] 2017-12-19 19:17
Tools such as help2man can help generate a man page.

**Comment by sigmavirus24** [comment] 2017-12-19 19:46
Duplicate of #248

**Comment by jakubroztocil** [comment] 2017-12-22 15:19
Any tips for good format/tools/workflow for the making a man page?

**Comment by sigmavirus24** [comment] 2017-12-22 21:04
Word of warning: Downstream Linux redistributors will not care about the man page you generate and in most cases generate one of equal or lesser quality. Further, `pip` doesn't always have the permissions to install man pages in the correct place. This probably shouldn't be much of a priority.

**Comment by pacoesteban** [comment] 2019-06-06 17:16
I would like to _re-activate_ this thread, as `httpie` is a CLI tool, it seems logical to have a man page for it at hand. The `--help` suggested by @stefan2904  seems incomplete and I cannot agree with @sigmavirus24, downstream (at least OpenBSD and others) cares about man pages. I do not see a reason not to use a good man page already distributed with the software ...

To the point, my suggestion is to change the `README.rst` for a proper man page using [mdoc](http://mandoc.bsd.lv/mdoc/), which could be used on all modern UNIX like systems (every linux distro, BSD, MacOSX, and many more). I volunteer for that. But I wanted to ask if you would consider this before investing any time on it.

I would leave a shorter `README.[md,rst]` with install instructions and some basic examples and the current animations. That will be the "face" on the github repo and can get you started. But I would convert the current documentation to an actual man page, one that can read in detail when needed, in a separate `tmux` pane or terminal, while actually working with `httpie`.

Later, that file will have to be maintained as you do now with the `rst` file.

What do you think ?

**Comment by pacoesteban** [comment] 2019-06-15 18:24
@jakubroztocil are you interested in this ?

Thanks.

**Comment by sigmavirus24** [comment] 2019-06-15 19:58
@pacoesteban why even bother rewriting in `mdoc` when there is `rst2man` utility that will generate the appropriate man page? 

The python community prefers `rst` and so we keeping our docs in that would be more maintainable and preserve doc quality.

**Comment by pacoesteban** [comment] 2019-06-16 11:39
I brought this back because the current readme is not really structured as a man page. I think it should be something like a refactored mix of the readme and `--help`. Also, it bugs me every time I have to check docs on this cli tool I use quite often (as @dequis was saying on #248). Besides, the `rst2man` utility you mention fails to generate the man page (and no, is not because of the images at the front of the file).

Of course is not my intention to try to impose my view on how docs should be to the python community or to this project, and I see little interest on this.

So, do you think the current readme could be modified in a way that some tool like `rst2man` could be used to generate a man page ? "Not perfect man page is better than no man page".

**Comment by sigmavirus24** [comment] 2019-06-16 14:24
I'm not a maintainer but I definitely agree that "an imperfect man page is better than none at all". As for my comment, earlier, Debian and Fedora have outright refused to use man pages bundled in projects I've worked on (e.g., OpenStack CLI tooling) in the past. Combine that with the understanding that `pip` on most Linux distributions is intentionally patched to disallow installation beyond user-scope and you've got the perfect recipe for "This is something that benefits very few people in practice". Especially when you consider that Debian and Fedora variants often pin old versions so adding man pages only helps people a few years in the future.

**Comment by deed02392** [comment] 2019-11-07 13:48
I have made an alias for `man httpie` that does `open https://httpie.org/doc` xD

**Comment by Almad** [comment] 2021-03-05 14:41
Would `http --help` be viable as a manpage? Based on what I see from the discussion here, it seems to me like a better "minimal" option.

But as mentioned, this is kind of a moot point if package maintainers wouldn't use it.

In that respect, I love the @deed02392's solution the most ^_^

**Comment by ducaale** [comment] 2022-06-12 18:29
Since HTTPie 3.2 comes with man pages, should this issue be closed?

**Comment by jakubroztocil** [comment] 2022-06-12 20:19
HTTPie now includes man pages — https://httpie.io/blog/httpie-3.2.0 🎉

**Closed by jakubroztocil** 2022-06-12 20:19 UTC
Labels: enhancement, docs
