### ISSUE TITLE
can't use multiple HTTP Headers with the same name

### ISSUE THREAD

**Issue by cythrawll** [httpie/httpie#130] opened 2013-02-21 22:51 UTC
In HTTP it allows multiple headers with the same name.  However, when I went to test
webapp that seems to break when IE10 sends multiple cookie headers, I can't use httpie to test it as it only puts in the last header value in the request.

example:

```bash
$ http -v example.org Cookie:foo1=bar1 User-Agent:BAM\1.0 Cookie:foo2=bar2
```

Current output:

```http
GET / HTTP/1.1
Accept: _/_
Accept-Encoding: gzip, deflate, compress
Cookie: foo2=bar2
Host: example.org
User-Agent: BAM1.0

//response omitted
```

Expected output:

```
GET / HTTP/1.1
Accept: _/_
Accept-Encoding: gzip, deflate, compress
Cookie: foo1=bar1
Cookie: foo2=bar2
Host: example.org
User-Agent: BAM1.0
```

Really HTTP headers should be represented as a case-insensitive MultiMap of some sort, not a  Dict.

**Comment by steven-lai** [comment] 2018-01-16 01:05
The suggested workaround of using: `HEADER:"VAL_1, VAL_2` doesn't quite work. I'm not sure if this is because of the server I'm using (Finatra). I'm logging the headers and the following is the results of using `curl` vs `httpie`.

Using `curl`:
`HEADER MAP=Map(Host -> localhost:9999, User-Agent -> curl/7.43.0, Accept -> */*, FOO -> first, FOO -> second)`

Using `httpie`
`HEADER MAP=Map(Host -> localhost:9999, User-Agent -> HTTPie/0.9.9, Accept-Encoding -> gzip, deflate, Accept -> */*, Connection -> keep-alive, FOO -> first, second)`

**Comment by LuckyDenis** [comment] 2019-04-24 18:47
I found what the problem is, can I take this task?

**Comment by steven-lai** [comment] 2019-04-24 21:08
I can't answer whether you can take this or not but I'm interested in what the problem is, can you provide some details?

**Comment by LuckyDenis** [comment] 2019-04-25 08:38
https://github.com/jakubroztocil/httpie/blob/master/httpie/input.py#L133 
Here we give our arguments to a parser built into a Python, and inside it uses dict instead of multdict resulting in key mashing. I just wanted to ask the community - in what form it is better to solve it. 1. There is the idea, or completely rewrite the logic of parsing, 2. Just add a function that will glue the value of the same keys.

**Comment by tgr** [comment] 2021-01-02 07:27
As noted in the upstream bug, RFC 7230 [says](https://tools.ietf.org/html/rfc7230#section-3.2.2) *A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception.* The RFC is not very clear about it but the only well-known exception seems to be `Set-Cookie`.

So httpie could just give some sort of warning on repeated headers, as such requests tend to be incorrect.

**Comment by Almad** [comment] 2021-02-03 14:51
Requests implemented MultiDict in https://github.com/kennethreitz/requests/issues/1155 , but it works for response only. 

Also, they [don't support multiple header field lines](https://github.com/psf/requests/issues/1155#issuecomment-236012970), they'd get combined into a single line as per RFC. We could do that in httpie as well. 

The complete fix would need to use urllib3 directly.

**Comment by Ousret** [comment] 2021-02-13 01:19
Something so simple yet so unsupported nowadays. Except for httpx. Also I have made something basic to help resolving issues with headers. Check out https://github.com/Ousret/kiss-headers if anyone is looking for a solution.

**Closed** 2021-10-31 14:04 UTC
Labels: bug, planned
