### ISSUE TITLE
-4 and -6 options, like curl

### ISSUE THREAD

**Issue by glyph** [httpie/httpie#569] opened 2017-03-10 23:01 UTC
It would be great if `-4` and `-6` were honored in the same way `curl` does, which is to say, only attempt to connect to IPv4 addresses, and only attempt to connect to IPv6 addresses.

Thank you!

**Comment by jakubroztocil** [comment] 2017-03-10 23:16
The `-4` / `-6` switches have come up before but the underlying Requests library apparently still doesn't provide support for this. it *might* be possible to implement this via a custom adapter, though. Related:  https://github.com/kennethreitz/requests/issues/1691

**Comment by sigmavirus24** [comment] 2017-03-13 19:30
@jakubroztocil if that custom adapter doesn't replace urllib3, that's still not possible. This needs to be made available in urllib3, not requests, for the adapter to work best (unless you plan to do a look up prior to urllib3). The benefit of trying to push this into urllib3 is the fact that we retry connecting if a particular IP returned by getaddrinfo is not responsive. If you pick one at random from getaddrinfo, then you're losing functionality.

**Comment by benjamingarcia** [comment] 2019-12-23 17:04
Hi! any update?

**Comment by kimbo** [comment] 2019-12-24 15:43
If urllib3 does something like [this patch](https://gitlab.com/snippets/1900824), you could write a HTTPAdapter for requests to get it to work.

**Comment by BoboTiG** [comment] 2021-09-17 14:30
Closing as duplicate of #94.

**Closed by BoboTiG** 2021-09-17 14:30 UTC
