### ISSUE TITLE
verbose output should show SSL/TLS details

### ISSUE THREAD

**Issue by pmeister** [httpie/httpie#1011] opened 2021-01-08 19:18 UTC
I'd like the see httpie's verbose output include some details of the SSL handshake and certificate, like curl's verbose output does:

for example:

```
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384

* Server certificate:
*  subject: C=US; ST=California; L=Redwood Shores; O=Oracle Corporation; CN=webservices.netsuite.com
*  start date: May 20 00:00:00 2020 GMT
*  expire date: Aug 19 12:00:00 2021 GMT
*  subjectAltName: host "rest.netsuite.com" matched cert's "rest.netsuite.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Secure Site ECC CA-1
*  SSL certificate verify ok.

```

**Comment by Almad** [comment] 2021-01-20 14:15
This could be implemented as adding additional flags to `-p`, in this case potentially `S` for SSL?

It probably shouldn't be part of `--verbose` since it would break the pipe chainability with other commands.

**Comment by patpolster** [comment] 2021-05-03 14:52
> I'd like the see httpie's verbose output include some details of the SSL handshake and certificate, like curl's verbose output does:
> 
> for example:
> 
> ```
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
> 
> * Server certificate:
> *  subject: C=US; ST=California; L=Redwood Shores; O=Oracle Corporation; CN=webservices.netsuite.com
> *  start date: May 20 00:00:00 2020 GMT
> *  expire date: Aug 19 12:00:00 2021 GMT
> *  subjectAltName: host "rest.netsuite.com" matched cert's "rest.netsuite.com"
> *  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Secure Site ECC CA-1
> *  SSL certificate verify ok.
> ```

**Comment by kindlehl** [comment] 2021-05-06 20:24
This would be very handy.

**Comment by isidentical** [comment] 2021-12-28 12:12
Duplicate of #826.

**Closed by isidentical** 2021-12-28 12:12 UTC
Labels: needs product design
